doctrine:
  dbal:
    url: "%env(resolve:DATABASE_URL)%"
    profiling_collect_backtrace: "%kernel.debug%"

  orm:
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    mappings:
      App:
        type: attribute
        dir: "%kernel.project_dir%/src/Entity"
        prefix: "App\\Entity"
        is_bundle: false
