doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    profiling_collect_backtrace: '%kernel.debug%'

  orm:
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true

