vich_uploader:
    db_driver: orm
    
    mappings:
        visites:
            uri_prefix: /images/visites
            upload_destination: '%kernel.project_dir%/public/images/visites'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
